### ISSUE TITLE
prior art: DomTerm

### ISSUE THREAD

**Issue by PerBothner** [christianparpart/terminal-good-image-protocol#10]
It would be nice if you mentioned [DomTerm](https://domterm.org).  You can use the following text as you find suitable

DomTerm's image support appeared in 2016.

Does not use a specific image protocol, but has an "insert HTML" protocol.  The typical way to insert an image is to insert an HTML `<img>` element, with the `src` attribute using a `data:` URL scheme, with the actual data inline as base64.  Any image format supported by the underlying browser engine (typicall png, gif, or jpeg) is allowed.

The `<img>` element can contain attributes such as `width`, `height`,`alt` and options to add scrollbars.  The `domterm image` command-line command provides options for setting many of these.

The resulting image is treated as an extra-large cell.  (DomTerm supports variable-width fonts and "cells, as well as variable-height rows.)

SVG images and Sixel are also supported.

**Comment by christianparpart** [comment]
Hey @PerBothner. Many thanks for participating! Of course i can and will add DomTerm's image support to the prior art section. I just didn't take too much time to look into the web tech terminals - i should have done that.

**Comment by christianparpart** [comment]
FYI: I've taken a slightly modified subset of your text proposal above. This draft spec only cares about actual prior art protocols, not terminals per-se, so it won't mention any other already mentioned image protocol (such as Sixel) or what CLI tool is provided. 

p.s.: I've also accidentally pushed into the `preview` branch, which automatically creates a prerelease. I decided to keep that, so we all have an up-to-date PDF/md snapshot for those who do not prefer reading LaTeX sources. :-)
