### ISSUE TITLE
image data transport encoding

### ISSUE THREAD

**Issue by christianparpart** [christianparpart/terminal-good-image-protocol#6]
While Base64  is the safest choice and has the broadest availability, it should thus definitely be supported by the spec.

We can evaluate whether or not a second more size-optimal transport encoding would make sense to require.

Egmont suggested Base85, Base192 and other more aggressive BaseNN-based ones.

But is it worth it?

**Comment by jerch** [comment]
If you ask me - no it is not worth the hassles. BASE64 is a cheapo calc and so ubiquitous available with highly optimized and well tested implementations, that I see no benefit in a slightly better compression rate.

**Comment by christianparpart** [comment]
I actually agree here. Especially for a v1 spec.
